all_config:
 github_token: xxxxxx
 github_proxy: xxxxxx
 dingding:
   - enable: 1
   - webhook: xxxxxx
   - secretKey: xxxxxx
 feishu:
   - enable: 1
   - webhook: xxxxxx
   - secretKey: xxxxxx
 server:
   - enable: 0
   - sckey: xxxxxx
 tgbot:
   - enable: 0
   - token: xxxxxx
   - group_id: xxxxxx
 pushplus:
   - enable: 0
   - token: xxxxxx
 translate:
  - enable: 0
 black_user:
   - AlAIAL90